/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrigonometryRouteImport } from './routes/trigonometry'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ScientificRouteImport } from './routes/scientific'
import { Route as ProbabilityRouteImport } from './routes/probability'
import { Route as PercentageRouteImport } from './routes/percentage'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as GrapherRouteImport } from './routes/grapher'
import { Route as GeometryRouteImport } from './routes/geometry'
import { Route as EquationsRouteImport } from './routes/equations'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculusRouteImport } from './routes/calculus'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AlgebraRouteImport } from './routes/algebra'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrigonometryRoute = TrigonometryRouteImport.update({
  id: '/trigonometry',
  path: '/trigonometry',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ScientificRoute = ScientificRouteImport.update({
  id: '/scientific',
  path: '/scientific',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbabilityRoute = ProbabilityRouteImport.update({
  id: '/probability',
  path: '/probability',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentageRoute = PercentageRouteImport.update({
  id: '/percentage',
  path: '/percentage',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const GrapherRoute = GrapherRouteImport.update({
  id: '/grapher',
  path: '/grapher',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryRoute = GeometryRouteImport.update({
  id: '/geometry',
  path: '/geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const EquationsRoute = EquationsRouteImport.update({
  id: '/equations',
  path: '/equations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculusRoute = CalculusRouteImport.update({
  id: '/calculus',
  path: '/calculus',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgebraRoute = AlgebraRouteImport.update({
  id: '/algebra',
  path: '/algebra',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/algebra': typeof AlgebraRoute
  '/calculator': typeof CalculatorRoute
  '/calculus': typeof CalculusRoute
  '/contact': typeof ContactRoute
  '/converter': typeof ConverterRoute
  '/equations': typeof EquationsRoute
  '/geometry': typeof GeometryRoute
  '/grapher': typeof GrapherRoute
  '/matrix': typeof MatrixRoute
  '/percentage': typeof PercentageRoute
  '/probability': typeof ProbabilityRoute
  '/scientific': typeof ScientificRoute
  '/statistics': typeof StatisticsRoute
  '/trigonometry': typeof TrigonometryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/algebra': typeof AlgebraRoute
  '/calculator': typeof CalculatorRoute
  '/calculus': typeof CalculusRoute
  '/contact': typeof ContactRoute
  '/converter': typeof ConverterRoute
  '/equations': typeof EquationsRoute
  '/geometry': typeof GeometryRoute
  '/grapher': typeof GrapherRoute
  '/matrix': typeof MatrixRoute
  '/percentage': typeof PercentageRoute
  '/probability': typeof ProbabilityRoute
  '/scientific': typeof ScientificRoute
  '/statistics': typeof StatisticsRoute
  '/trigonometry': typeof TrigonometryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/algebra': typeof AlgebraRoute
  '/calculator': typeof CalculatorRoute
  '/calculus': typeof CalculusRoute
  '/contact': typeof ContactRoute
  '/converter': typeof ConverterRoute
  '/equations': typeof EquationsRoute
  '/geometry': typeof GeometryRoute
  '/grapher': typeof GrapherRoute
  '/matrix': typeof MatrixRoute
  '/percentage': typeof PercentageRoute
  '/probability': typeof ProbabilityRoute
  '/scientific': typeof ScientificRoute
  '/statistics': typeof StatisticsRoute
  '/trigonometry': typeof TrigonometryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/algebra'
    | '/calculator'
    | '/calculus'
    | '/contact'
    | '/converter'
    | '/equations'
    | '/geometry'
    | '/grapher'
    | '/matrix'
    | '/percentage'
    | '/probability'
    | '/scientific'
    | '/statistics'
    | '/trigonometry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/algebra'
    | '/calculator'
    | '/calculus'
    | '/contact'
    | '/converter'
    | '/equations'
    | '/geometry'
    | '/grapher'
    | '/matrix'
    | '/percentage'
    | '/probability'
    | '/scientific'
    | '/statistics'
    | '/trigonometry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/algebra'
    | '/calculator'
    | '/calculus'
    | '/contact'
    | '/converter'
    | '/equations'
    | '/geometry'
    | '/grapher'
    | '/matrix'
    | '/percentage'
    | '/probability'
    | '/scientific'
    | '/statistics'
    | '/trigonometry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlgebraRoute: typeof AlgebraRoute
  CalculatorRoute: typeof CalculatorRoute
  CalculusRoute: typeof CalculusRoute
  ContactRoute: typeof ContactRoute
  ConverterRoute: typeof ConverterRoute
  EquationsRoute: typeof EquationsRoute
  GeometryRoute: typeof GeometryRoute
  GrapherRoute: typeof GrapherRoute
  MatrixRoute: typeof MatrixRoute
  PercentageRoute: typeof PercentageRoute
  ProbabilityRoute: typeof ProbabilityRoute
  ScientificRoute: typeof ScientificRoute
  StatisticsRoute: typeof StatisticsRoute
  TrigonometryRoute: typeof TrigonometryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trigonometry': {
      id: '/trigonometry'
      path: '/trigonometry'
      fullPath: '/trigonometry'
      preLoaderRoute: typeof TrigonometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scientific': {
      id: '/scientific'
      path: '/scientific'
      fullPath: '/scientific'
      preLoaderRoute: typeof ScientificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probability': {
      id: '/probability'
      path: '/probability'
      fullPath: '/probability'
      preLoaderRoute: typeof ProbabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentage': {
      id: '/percentage'
      path: '/percentage'
      fullPath: '/percentage'
      preLoaderRoute: typeof PercentageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grapher': {
      id: '/grapher'
      path: '/grapher'
      fullPath: '/grapher'
      preLoaderRoute: typeof GrapherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry': {
      id: '/geometry'
      path: '/geometry'
      fullPath: '/geometry'
      preLoaderRoute: typeof GeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equations': {
      id: '/equations'
      path: '/equations'
      fullPath: '/equations'
      preLoaderRoute: typeof EquationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculus': {
      id: '/calculus'
      path: '/calculus'
      fullPath: '/calculus'
      preLoaderRoute: typeof CalculusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algebra': {
      id: '/algebra'
      path: '/algebra'
      fullPath: '/algebra'
      preLoaderRoute: typeof AlgebraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlgebraRoute: AlgebraRoute,
  CalculatorRoute: CalculatorRoute,
  CalculusRoute: CalculusRoute,
  ContactRoute: ContactRoute,
  ConverterRoute: ConverterRoute,
  EquationsRoute: EquationsRoute,
  GeometryRoute: GeometryRoute,
  GrapherRoute: GrapherRoute,
  MatrixRoute: MatrixRoute,
  PercentageRoute: PercentageRoute,
  ProbabilityRoute: ProbabilityRoute,
  ScientificRoute: ScientificRoute,
  StatisticsRoute: StatisticsRoute,
  TrigonometryRoute: TrigonometryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
